openapi: 3.0.3
info:
  version: 1.0.0
  title: "[CircleCI + Kong] JSON Placeholder"
  description: See https://jsonplaceholder.typicode.com/
  x-kubernetes-ingress-metadata:
    name: jsonplaceholder
servers:
  - url: http://a3f3a529480354df8bab007b3ab4d2af-285095836.us-west-2.elb.amazonaws.com
    description: JSON Placeholder
    x-kubernetes-service:
      spec:
        ports:
          - port: 3000
      metadata:
        name: jsonplaceholder-svc
paths:
  /posts:
    get:
      description: Returns all posts
      tags: ["Posts"]
      operationId: "getPosts"
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/PostsList"

  /posts/{id}:
    get:
      description: Returns a post by id
      tags: ["Posts"]
      operationId: "getPost"
      parameters:
        - name: id
          in: path
          required: true
          description: The user id.
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful response
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: Post not found

components:
  schemas:
    PostsList:
      "type": "array"
      "items":
        $ref: "#/components/schemas/Post"
    Post:
      "type": "object"
      "required":
        - "id"
        - "userId"
        - "title"
        - "completed"
      "properties":
        id:
          type: "integer"
        userId:
          type: "integer"
        title:
          type: "string"
        completed:
          type: "string"
