version: 2.1

orbs:
  newman: postman/newman@0.0.2
  node: circleci/node@4.7.0

executors:
  ci-runner:
    machine: true
    resource_class: ci-runner/open-tech-staging

workflows:
  deployment:
    jobs:
      - deploy

jobs:
  deploy:
    executor: ci-runner
    steps:
      - checkout
      - node/install
      - node/install-npm
      - node/install-packages
      - run: npm install -g newman
      - run:
          command: >
            newman run
            --env-var=baseUrl=https://kubernetes.default.svc
            --env-var=token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            --ssl-client-cert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            '"./postman/collections/[CircleCI + Kong] JSONPlaceholder Deployment_296499c6-d8ba-4cf6-ab60-b40a10b02104.json"'

#    steps:
#      - checkout
#      - kubernetes/install-kubectl
#      - kubernetes/create-or-update-resource:
#          get-rollout-status: true
#          resource-file-path: ./ci/deployment.yaml

# my-job:
#    executor: my-runner
#    steps:
#      - checkout
#      - run: ./ci/kubecurl.sh
#      - run: echo "Hello from my custom runner!"
# newman-collection-run:
#   machine: true
#   resource_class: ci-runner/open-tech-staging
#   executor:
#     name: newman/postman-newman-docker
#     tag: 5.2.0
#   steps:
#     - checkout
#     - newman/newman-run:
#         collection: '"./postman/collections/[CircleCI + Kong] JSONPlaceholder Deployment_296499c6-d8ba-4cf6-ab60-b40a10b02104.json"'
#         additional_options: >
#           --env-var=baseUrl=https://kubernetes.default.svc
#           --env-var=token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
#           --ssl-client-cert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
# orbs:
#   newman: postman/newman@0.0.2
#   node: circleci/node@4.7.0
#
# version: 2.1
#
# jobs:
#   api-gateway:
#     executor:
#       name: newman/postman-newman-docker
#       tag: 5.2.0
#     steps:
#       - checkout
#       - newman/newman-run:
#           collection: '"./postman/collections/[CircleCI + Kong] JSON Placeholder Deployment_c897c8b0-1aa0-4a69-bf7c-340af7756052.json"'
#
# workflows:
#   main:
#     jobs:
#       - node/test
#       - api-gateway:
#           filters:
#             branches:
#               only: /^release-.*/
