apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonplaceholder-deploy
  labels:
    app: jsonplaceholder-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsonplaceholder-deploy
  template:
    metadata:
      labels:
        app: jsonplaceholder-deploy
    spec:
      containers:
        - name: newman
          image: postman/newman:alpine
          args:
            - run
            - --env-var=baseUrl=https://kubernetes.default.svc
            - --env-var=token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            - --ssl-client-cert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - ./postman/collections/[CircleCI\ +\ Kong]\ JSONPlaceholder\ Deployment_296499c6-d8ba-4cf6-ab60-b40a10b02104.json
